- hosts: localhost
  connection: local
  become: true
  tasks:
    - name: pull dotfile repo
      git:
        repo: https://github.com/FredrikMWold/.dotfiles.git
        dest: ~/.dotfiles
    - name: add vscode repository
      apt_repository:
        repo: deb [arch=amd64] https://packages.microsoft.com/repos/vscode stable main
    - name: add flathub repository
      flatpak_remote:
        name: flathub
        flatpakrepo_url: https://dl.flathub.org/repo/flathub.flatpakrepo
    - name: install stow
      apt:
        name: stow
        state: latest
    - name: install htop
      apt:
        name: htop
        state: latest
    - name: install vscode
      apt:
        name: code
        state: latest
    - name: install chrome
      apt:
        name: google-chrome-stable
        state: latest
    - name: install flameshot
      apt:
        name: flameshot
        state: latest
    - name: install zsh
      apt:
        name: zsh
        state: latest
    - name: install teams
      flatpak:
        name: com.github.IsmaelMartinez.teams_for_linux
        state: present
    - name: install slack
      flatpak:
        name: com.slack.Slack
        state: present
    - name: check if oh-my-zsh is installed
      stat:
        path: ~/.oh-my-zsh
      register: oh_my_zsh
      become_user: fredrik
    - name: install oh-my-zsh
      shell: sh -c "$(wget -O- https://raw.githubusercontent.com/ohmyzsh/ohmyzsh/master/tools/install.sh)" "" --keep-zshrc
      when: not oh_my_zsh.stat.exists
      become_user: fredrik
    - name: remove old .zshrc
      file:
        path: ~/.zshrc
        state: absent
      become_user: fredrik
    - name: symlink dotfiles with stow
      shell: cd ~/.dotfiles && stow config
      become_user: fredrik
    - name: clear font cache
      shell: fc-cache -f -v
      become_user: fredrik
